# Generated by Django 3.2 on 2022-06-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feed_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='guide',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
