# Generated by Django 3.2 on 2022-06-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feed_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='published_time',
            field=models.DateTimeField(verbose_name='Published Time'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_modified',
            field=models.TextField(blank=True, null=True),
        ),
    ]
