# Generated by Django 3.2 on 2022-06-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220627_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='guide',
            new_name='guid',
        ),
    ]
