# Generated by Django 3.2 on 2022-06-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userfeed_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
            preserve_default=False,
        ),
    ]
